# Generated by Django 2.2.10 on 2023-03-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=300)),
                ('data_path', models.CharField(max_length=300)),
                ('thumbnail_path', models.CharField(max_length=300)),
                ('fish_group', models.CharField(max_length=100)),
                ('year_reading_manual', models.IntegerField(default=-1)),
                ('year_reading_automated', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='OtolithImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=300)),
                ('data_path', models.CharField(max_length=300)),
                ('thumbnail_path', models.CharField(max_length=300)),
                ('fish_group', models.CharField(max_length=100)),
                ('year_reading_manual', models.IntegerField(default=-1)),
                ('year_reading_automated', models.IntegerField(default=-1)),
            ],
        ),
    ]
